# Site settings
title: Eric Englin
email: ericenglin@gmail.com
url: https://ericenglin.github.io
description: ""
keywords: "Harvard Kennedy School, Public Policy, Transportation, U.S. Department of Transportation, Data Science"
skills: "Public Policy - Data Science - Social Good"
meta_author: Englin Eric

# Google webmaster tools
google_verify: HsmXETSv6OAjLz580caTk_ywDsWHOU0EuVAuCCtcDpM

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
#Â - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: ericenglin

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  primary-rgb: "24,288,156" #"128,179,255"
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: Eric Englin
  location: Location
  social: Around the Web
  credits:

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: linkedin
    url: https://www.linkedin.com/in/ericenglin/
  - title: github
    url: http://github.com/ericenglin

# Postal address (add as many lines as necessary)
address:
  - line: Washington, D.C.


# Build settings
markdown: kramdown
permalink: pretty
