title: Eric Englin # your name (or website title) here
logo: "/images/eric-englin.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Graduate Student at Harvard Kennedy School
  <br><br>
  Working on data science projects to support the public good and improve government agencies.
  <br><br>
  <a href="https://www.linkedin.com/in/ericenglin/">View My LinkedIn Profile</a>

theme: jekyll-theme-clean-blog
google_analytics: UA-151918240-1 # your Google Analytics tracking ID here
